language: rust

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
    - libsd2l-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev

script:
  - cargo test --verbose
