language: rust

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
    - libsfml-dev
    - libcsfml-dev

script:
  - cargo test --verbose
